### ISSUE TITLE
Missing information about JRE version

### ISSUE THREAD

**Issue by viorelAlexandrescu** [garimpeiro-it/java-key-sender#1]
I've noticed this project is used as a dependency in the node-key-sender module.

In the description, there is a statement saying: "It uses a jar file (Java), so Java Run Time is required on the operational system you are running your node project.".

I've done some digging and it seems you are using some Java 8 features, but in the README, you haven't placed any information about what runtime version of Java is required.

Would you please add some information to solve this issue? Thank You

**Comment by fernandohu** [comment]
Done! Thank you.
